use font_map_core::{font::Font, FontCodegenExt};

const FONT_BYTES: &[u8] = include_bytes!("font.ttf");

fn main() {
    println!("cargo:rerun-if-changed=font.ttf");

    let font = Font::new(FONT_BYTES).unwrap();
    let code = font.gen_enum("Icon").to_string();

    let code = [
        "//! Autogenerated by `build.rs` - do not modify\n
        "
        .to_string(),
        code,
    ]
    .join("\n");

    std::fs::write("src/font_generated.rs", code).unwrap();

    //
    // Run `cargo fmt` against the new file
    std::process::Command::new("cargo")
        .arg("fmt")
        .arg("--")
        .arg("src/font_generated.rs")
        .output()
        .expect("Failed to run `cargo fmt`");
}
