name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run all-feature tests
      run: cargo test --lib --all-features --workspace

    - name: Run no-features tests
      run: cargo test --lib --no-default-features --workspace

    - name: Run fmt
      run: cargo fmt --check
    
    - name: Run clippy
      run: cargo clippy --all-features
      
    - name: Check if the README is up to date.
      run: |
        cargo install cargo-rdme
        cargo rdme --check